# Generated by Django 4.1.7 on 2023-03-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profiles_image',
            new_name='profile_image',
        ),
    ]
